name: Update Files List

on:
  push:
    paths:
      - '*.sh' # Запускать, только если изменились скрипты

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate files.txt
        run: |
          # Находим все .sh файлы, кроме самого загрузчика, и записываем в files.txt
          ls *.sh | grep -v "downloader.sh" > files.txt

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add files.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update files.txt" && git push)
